Adds Vagrant and Virtual Box version checks.
- Vagrant version check is also an enforcement. `vagrant` will abort if version
in < 1.8.0

- VirtualBox >= 5.0. Because of the limitations in the Vagrantfile language
spec, VirtualBox version check does not abort the process. It only displays
a verbose error on screen.
==========================================
ERROR: Virtual Box version should be >=5.0
==========================================

Signed-off-by: Vikrant Balyan <vijayvikrant84@gmail.com>